{% set name = "floralatin-hubble-sdk3" %}
{% set version = "1.0.2" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43d766eddb7486034d3efa3ce9350b3bfdbc5bfb79cc3edfcd3dfd905f75f0e3

build:
  number: 0
  entry_points:
    - jina-auth=hubble.__main__:main
    - jina-hub=hubble.executor.__main__:main
    - docker-credential-jina-hubble=hubble.dockerauth:main
  script: '{{ PYTHON }} -m pip install . -vv'

requirements:
  host:
    - aiohttp
    - cryptography
    - docker-py
    - filelock
    - importlib-metadata
    - pathspec
    - python
    - pyyaml
    - requests
    - rich
  run:
    - aiohttp
    - cryptography
    - docker-py
    - filelock
    - importlib-metadata
    - pathspec
    - python
    - pyyaml
    - requests
    - rich

# test:
#   imports:
#     - hubble
#     - hubble.client
#     - hubble.executor
#     - hubble.executor.parsers
#     - hubble.parsers
#     - hubble.utils
#   commands:
#     - jina-auth --help
#     - jina-hub --help
#     - docker-credential-jina-hubble --help

about:
  home: https://github.com/jina-ai/hubble-client-python/
  license: Proprietary
  license_family: PROPRIETARY
  license_file: null
  summary: SDK for Hubble API at Jina AI.
  doc_url: null
  dev_url: null

extra:
  recipe-maintainers:
    - your-github-id-here
