name: Deploy

on:
  release:
    types:
      - "released"
jobs:
  style-lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: list info
      run: |
        pwd
        ls 
        ls conda
        ls conda/floralatin-hubble-sdk/
        echo github.ref: ${{ github.ref }}
    