name: CD

on:
  push:
    branches:
      - main
      - alpha
      - beta
  release:
    types:
      - "released"
  

jobs:
  style-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install requirements
        run: make init
      - name: Lint with flake8, black and isort
        run: make style
      - name: Run tests
        run: make test
        env:
          JINA_AUTH_TOKEN: ${{secrets.JINA_AUTH_TOKEN}}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install semantic-release
        run: npm install --global semantic-release @semantic-release/git semantic-release-pypi
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install requirements
        run: make init
      - name: Install setuptools
        run: python -m pip install --upgrade setuptools wheel twine
      - name: Release pypi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: npx semantic-release

  
  release-conda:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        project-name: ["floralatin-hubble-sdk3"]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.7
          conda-channels: anaconda, conda-forge
      - name: install conda-build
        run: conda install -y conda-build anaconda-client
      - name: conda skeleton pypi ${{ matrix.project-name }}
        run: conda skeleton pypi ${{ matrix.project-name }}  --output-dir conda

      - name: generate conda recipe
        run: python scripts/generate-conda-recipe.py

      - name: conda build
        run: conda build -c conda-forge conda --output-folder anaconda

      - name: anaconda login 
        run: anaconda login --username floralatin --password TANkai521
      - name: anaconda upload 
        run: anaconda -c conda-forge --label main anaconda/*/${{ matrix.project-name }}*.tar.bz2
